import type { WeaponDef, WeaponId, BuildingDef, LevelDef } from "./types";

export const WEAPONS: Record<WeaponId, WeaponDef> = {
  basic: {
    id: "basic",
    name: "普通炮弹",
    emoji: "💣",
    color: "#FFD666",
    desc: "基础高爆弹，命中爆炸",
    damage: 50,
    blastRadius: 50,
    unlocked: true,
  },
  fire: {
    id: "fire",
    name: "燃烧弹",
    emoji: "🔥",
    color: "#FF7A1A",
    desc: "爆炸+燃烧 2 秒持续伤害",
    damage: 35,
    blastRadius: 60,
    burn: 12,
    unlocked: false,
  },
  bunker: {
    id: "bunker",
    name: "钻地弹",
    emoji: "⚙",
    color: "#B388FF",
    desc: "穿透建筑继续飞行",
    damage: 60,
    blastRadius: 40,
    pierce: true,
    unlocked: false,
  },
  cluster: {
    id: "cluster",
    name: "集束弹",
    emoji: "💥",
    color: "#E5353B",
    desc: "空中分裂为 3 颗子弹",
    damage: 40,
    blastRadius: 45,
    split: 3,
    unlocked: false,
  },
};

export const BUILDINGS: Record<string, BuildingDef> = {
  den: {
    id: "den",
    name: "电诈窝点",
    emoji: "🏢",
    hp: 50,
    score: 100,
    color: "#9FE3FF",
    fraudType: "电诈窝点",
    w: 70,
    h: 90,
  },
  dorm: {
    id: "dorm",
    name: "诈骗宿舍",
    emoji: "🏨",
    hp: 70,
    score: 150,
    color: "#FFB020",
    fraudType: "电诈人员宿舍",
    w: 70,
    h: 110,
  },
  server: {
    id: "server",
    name: "诈骗服务器",
    emoji: "🖥",
    hp: 40,
    score: 200,
    color: "#1AD670",
    fraudType: "诈骗通信中枢",
    w: 60,
    h: 70,
    bonus: 200,
  },
  armored: {
    id: "armored",
    name: "加固堡垒",
    emoji: "🏰",
    hp: 140,
    score: 300,
    color: "#B388FF",
    fraudType: "电诈核心堡垒",
    w: 80,
    h: 100,
    armored: true,
  },
};

export const LEVELS: LevelDef[] = [
  {
    id: "myawaddy",
    name: "妙瓦底新手园",
    subtitle: "MYAWADDY · LEVEL 1",
    terrain: "easy",
    ammo: 5,
    buildings: [
      { typeId: "den", x: 620, y: 460 },
      { typeId: "dorm", x: 720, y: 460 },
      { typeId: "server", x: 820, y: 460 },
    ],
    unlockWeapon: "fire",
    briefing: "妙瓦底是缅东最大的电诈园区之一。摧毁 3 个基础建筑即可完成首战。",
    fraudSummary: "妙瓦底园区涉及：网络赌博、杀猪盘、虚假投资诈骗",
  },
  {
    id: "kokang",
    name: "缅北中区园",
    subtitle: "KOKANG · LEVEL 2",
    terrain: "hills",
    ammo: 6,
    buildings: [
      { typeId: "dorm", x: 560, y: 460 },
      { typeId: "server", x: 660, y: 460 },
      { typeId: "den", x: 780, y: 460 },
      { typeId: "dorm", x: 860, y: 460 },
    ],
    unlockWeapon: "bunker",
    briefing: "缅北地形复杂，诈骗窝点加固。使用燃烧弹持续灼烧。",
    fraudSummary: "缅北园区涉及：冒充公检法、刷单返利、虚假贷款诈骗",
  },
  {
    id: "hq",
    name: "总部核心园",
    subtitle: "HEADQUARTERS · LEVEL 3",
    terrain: "fortress",
    ammo: 7,
    buildings: [
      { typeId: "armored", x: 540, y: 460 },
      { typeId: "dorm", x: 660, y: 460 },
      { typeId: "server", x: 760, y: 460 },
      { typeId: "armored", x: 830, y: 460 },
      { typeId: "den", x: 900, y: 460 },
    ],
    unlockWeapon: "cluster",
    briefing: "总部核心堡垒！必须用钻地弹穿透装甲，集束弹覆盖全场。",
    fraudSummary: "总部园区涉及：跨境洗钱、APP 套路贷、虚假外汇平台",
  },
];

export function getWeapon(id: WeaponId): WeaponDef {
  return WEAPONS[id];
}
