import type { AgentDef, EnemyDef, Wave } from "./types";

export const AGENTS: AgentDef[] = [
  {
    id: "shen",
    name: "沈锋",
    role: "突击手",
    emoji: "🔫",
    hp: 120,
    attack: 22,
    range: 220,
    fireRate: 2.2,
    projectileSpeed: 520,
    color: "#FF7A1A",
    ult: "穿透射击",
    ultDesc: "对一整排敌人造成大量伤害",
    bio: "刑侦老炮，专攻杀猪盘资金链",
  },
  {
    id: "lin",
    name: "林书影",
    role: "通讯专家",
    emoji: "📡",
    hp: 80,
    attack: 14,
    range: 360,
    fireRate: 1.6,
    projectileSpeed: 620,
    color: "#00E5FF",
    ult: "信号干扰",
    ultDesc: "减速全场敌人 3 秒",
    slow: 0.5,
    bio: "反诈中心话务员，能识别每一句陷阱",
  },
  {
    id: "zhou",
    name: "周衡",
    role: "技术员",
    emoji: "💻",
    hp: 90,
    attack: 18,
    range: 280,
    fireRate: 1.1,
    projectileSpeed: 480,
    color: "#B388FF",
    ult: "数据风暴",
    ultDesc: "AOE 轰炸全场敌人",
    splash: 80,
    bio: "网安工程师，黑进过 7 个电诈窝点",
  },
  {
    id: "wang",
    name: "王婆婆",
    role: "社工师",
    emoji: "👵",
    hp: 140,
    attack: 10,
    range: 200,
    fireRate: 1.4,
    projectileSpeed: 360,
    color: "#52C41A",
    ult: "全民防线",
    ultDesc: "全队回血 + 基地护盾",
    bio: "社区反诈志愿者，专拆甜言蜜语",
  },
  {
    id: "su",
    name: "苏岩",
    role: "数据分析师",
    emoji: "📊",
    hp: 85,
    attack: 28,
    range: 300,
    fireRate: 1.0,
    projectileSpeed: 540,
    color: "#FFD666",
    ult: "精准狙击",
    ultDesc: "暴击率翻倍 5 秒",
    crit: 0.6,
    bio: "用数据模型锁定诈骗团伙",
  },
  {
    id: "chen",
    name: "陈默",
    role: "潜伏者",
    emoji: "🥷",
    hp: 100,
    attack: 32,
    range: 160,
    fireRate: 0.9,
    projectileSpeed: 700,
    color: "#E5353B",
    ult: "暗影刺杀",
    ultDesc: "瞬移到最强敌人身后一击",
    bio: "卧底三年，潜伏在电诈园区",
  },
];

export const ENEMIES: Record<string, EnemyDef> = {
  robot: {
    id: "robot",
    name: "话术机器人",
    emoji: "🤖",
    hp: 50,
    speed: 60,
    damage: 8,
    reward: 80,
    color: "#9FE3FF",
    fraudType: "话术脚本诈骗",
  },
  popup: {
    id: "popup",
    name: "假客服弹窗",
    emoji: "💬",
    hp: 80,
    speed: 50,
    damage: 12,
    reward: 120,
    color: "#FFB020",
    fraudType: "冒充客服诈骗",
  },
  threat: {
    id: "threat",
    name: "恐吓语音",
    emoji: "📞",
    hp: 130,
    speed: 40,
    damage: 18,
    reward: 180,
    color: "#E5353B",
    fraudType: "冒充公检法诈骗",
  },
  sweet: {
    id: "sweet",
    name: "甜言蜜语",
    emoji: "💕",
    hp: 90,
    speed: 55,
    damage: 10,
    reward: 150,
    color: "#FF7AB8",
    fraudType: "杀猪盘情感诈骗",
    heal: 12,
  },
  phish: {
    id: "phish",
    name: "钓鱼链接",
    emoji: "🎣",
    hp: 60,
    speed: 80,
    damage: 14,
    reward: 130,
    color: "#1AD670",
    fraudType: "钓鱼网站盗刷",
  },
  farmer: {
    id: "farmer",
    name: "卡农",
    emoji: "💳",
    hp: 220,
    speed: 35,
    damage: 28,
    reward: 400,
    color: "#B388FF",
    fraudType: "买卖银行卡洗钱",
  },
};

export const WAVES: Wave[] = [
  // Wave 1: 话术机器人 + 钓鱼链接
  {
    enemies: [
      { typeId: "robot", count: 4, interval: 1.2, lane: 0, delay: 0 },
      { typeId: "robot", count: 3, interval: 1.4, lane: 2, delay: 1 },
      { typeId: "phish", count: 3, interval: 1.6, lane: 1, delay: 2 },
    ],
  },
  // Wave 2: 假客服 + 甜言蜜语 + 话术机器人
  {
    enemies: [
      { typeId: "popup", count: 4, interval: 1.1, lane: 1, delay: 0 },
      { typeId: "sweet", count: 3, interval: 1.5, lane: 0, delay: 1.5 },
      { typeId: "robot", count: 4, interval: 1.0, lane: 2, delay: 3 },
      { typeId: "phish", count: 3, interval: 1.3, lane: 0, delay: 5 },
    ],
  },
  // Wave 3: 恐吓语音 + 甜言蜜语 + 卡农 boss
  {
    enemies: [
      { typeId: "threat", count: 3, interval: 1.4, lane: 0, delay: 0 },
      { typeId: "sweet", count: 3, interval: 1.3, lane: 1, delay: 1 },
      { typeId: "popup", count: 4, interval: 1.0, lane: 2, delay: 2 },
      { typeId: "farmer", count: 1, interval: 1, lane: 1, delay: 4 },
      { typeId: "threat", count: 2, interval: 1.2, lane: 2, delay: 6 },
    ],
  },
];

export function getAgent(id: string): AgentDef | undefined {
  return AGENTS.find((a) => a.id === id);
}
