// ====================================================================
// 反诈职业经理人 · v11 全面升级数据
// 独立文件，避免 data.ts / data.v8.ts 过大（渐进式拆分）
// 包含：
//   A1: 12 个新敌人（2026 Q3-Q4 新型诈骗 + AI 行为树）
//   A2: 3 个新 BOSS（F116/F117/F118，三阶段 + 剧情对白）
//   A3: 桥接 CodexEntry / RealCaseDef / CaseBreakdownDef
//   C2: 6 个受害者视角剧本（多结局 + 弱点情报奖励）
// ====================================================================

import type {
  EnemyDef,
  BossRushDef,
  BossDialogue,
  CodexEntry,
  RealCaseDef,
  CaseBreakdownDef,
  VictimSimScenario,
  CustomDifficultyConfig,
  CustomDifficultyPreset,
} from "./types";

// ====================================================================
// A1：12 个新敌人（2026 Q3-Q4 新型诈骗）
// 覆盖：AI 实时换脸 / 数字人民币 / 加密货币杀猪盘 / NFT / 元宇宙 / 智能合约 / AI 投顾 等
// 每个敌人沿用 v9 AI 行为树系统（disguise / flank / rush / enrage / split / fearAura 等）
// ====================================================================

export const ENEMIES_V11: Record<string, EnemyDef> = {
  // ===== F116 系：AI 实时换脸诈骗（3 种小怪） =====
  aiRealtimeFaceSwap: {
    id: "aiRealtimeFaceSwap",
    name: "AI 实时换脸",
    emoji: "🎞️",
    hp: 135,
    speed: 58,
    damage: 22,
    reward: 240,
    color: "#9C27B0",
    fraudType: "AI 实时换脸视频通话诈骗",
    element: "tech",
    ability: "invisible",
    shape: "mask",
    isNew: true,
    codexId: "codex_aiRealtimeFaceSwap",
    // v11 AI：间歇伪装成正常 NPC（视频通话中换脸，受害人难辨真伪）
    aiBehavior: {
      kind: "disguise",
      trigger: { chance: 0.4, cooldown: 3 },
      params: { disguiseDuration: 2.0 },
    },
  },
  aiBlackmail: {
    id: "aiBlackmail",
    name: "AI 换脸敲诈",
    emoji: "😈",
    hp: 110,
    speed: 62,
    damage: 24,
    reward: 220,
    color: "#B71C1C",
    fraudType: "AI 换脸合成不雅视频敲诈",
    element: "threat",
    ability: "fear",
    shape: "mask",
    isNew: true,
    codexId: "codex_aiBlackmail",
    // v11 AI：恐惧光环（半径 130），模拟"不转账就发布视频"恐吓
    aiBehavior: {
      kind: "fearAura",
      params: { auraRadius: 130 },
    },
  },
  deepfakeVideoCall: {
    id: "deepfakeVideoCall",
    name: "Deepfake 视频通话",
    emoji: "📹",
    hp: 95,
    speed: 70,
    damage: 18,
    reward: 200,
    color: "#6A1B9A",
    fraudType: "Deepfake 视频通话冒充领导",
    element: "tech",
    ability: "speedBoost",
    shape: "phone",
    isNew: true,
    codexId: "codex_deepfakeVideoCall",
    // v11 AI：绕侧 + 低血量加速，模拟视频通话从多渠道接入
    aiBehavior: {
      kind: "flank",
      trigger: { chance: 0.55, cooldown: 1.8 },
      secondary: "enrage",
    },
  },

  // ===== F117 系：数字人民币授权诈骗（3 种小怪） =====
  digitalRmbAuth: {
    id: "digitalRmbAuth",
    name: "数字人民币授权",
    emoji: "🪙",
    hp: 125,
    speed: 50,
    damage: 20,
    reward: 230,
    color: "#FF6F00",
    fraudType: "数字人民币钱包授权诈骗",
    element: "money",
    ability: "shield",
    shape: "wallet",
    isNew: true,
    codexId: "codex_digitalRmbAuth",
    // v11 AI：首次命中减半（授权页面伪装正规），副行为 rush（病毒式扩散）
    aiBehavior: {
      kind: "rush",
      trigger: { belowHpRatio: 0.5 },
      params: { speedMul: 1.5 },
      secondary: "disguise",
    },
  },
  fakeDigitalWallet: {
    id: "fakeDigitalWallet",
    name: "虚假数字钱包",
    emoji: "👛",
    hp: 160,
    speed: 42,
    damage: 26,
    reward: 260,
    color: "#F57C00",
    fraudType: "虚假数字货币钱包 APP 诈骗",
    element: "money",
    ability: "taunt",
    shape: "briefcase",
    isNew: true,
    codexId: "codex_fakeDigitalWallet",
    // v11 AI：嘲讽吸引投射物（伪造高收益吸引用户点击）
    aiBehavior: {
      kind: "disguise",
      trigger: { chance: 0.3, cooldown: 4 },
      params: { disguiseDuration: 2.5 },
    },
  },
  fakeSmartContract: {
    id: "fakeSmartContract",
    name: "虚假智能合约",
    emoji: "📜",
    hp: 90,
    speed: 75,
    damage: 16,
    reward: 210,
    color: "#FBC02D",
    fraudType: "虚假智能合约授权诈骗",
    element: "tech",
    ability: "speedBoost",
    shape: "hook",
    isNew: true,
    codexId: "codex_fakeSmartContract",
    // v11 AI：低血量瞬移到出口附近，模拟合约执行后资金瞬间被转走
    aiBehavior: {
      kind: "teleport",
      trigger: { belowHpRatio: 0.35 },
      params: { teleportToExitDist: 4 },
    },
  },

  // ===== F118 系：加密货币杀猪盘（3 种小怪） =====
  cryptoPigButcher: {
    id: "cryptoPigButcher",
    name: "加密杀猪盘",
    emoji: "🐖",
    hp: 180,
    speed: 38,
    damage: 28,
    reward: 280,
    color: "#E91E63",
    fraudType: "加密货币杀猪盘诈骗",
    element: "emotion",
    ability: "heal",
    shape: "heart",
    isNew: true,
    codexId: "codex_cryptoPigButcher",
    // v11 AI：治疗光环（半径 110），模拟"情感维持+虚假收益"互相支撑
    aiBehavior: {
      kind: "healAura",
      params: { healPerSec: 8, auraRadius: 110 },
    },
  },
  nftAirdropPhish: {
    id: "nftAirdropPhish",
    name: "NFT 空投钓鱼",
    emoji: "🖼️",
    hp: 85,
    speed: 82,
    damage: 14,
    reward: 190,
    color: "#00BCD4",
    fraudType: "NFT 空投钓鱼链接诈骗",
    element: "tech",
    ability: "split",
    shape: "hook",
    isNew: true,
    codexId: "codex_nftAirdropPhish",
    // v11 AI：死亡时分裂为 2 个钓鱼链接，模拟空投链接病毒式传播
    aiBehavior: {
      kind: "split",
      params: { splitTypeId: "phish" },
    },
  },
  metaverseLand: {
    id: "metaverseLand",
    name: "元宇宙土地",
    emoji: "🌌",
    hp: 145,
    speed: 48,
    damage: 22,
    reward: 250,
    color: "#7C4DFF",
    fraudType: "元宇宙虚拟土地诈骗",
    element: "emotion",
    ability: "taunt",
    shape: "window",
    isNew: true,
    codexId: "codex_metaverseLand",
    // v11 AI：绕侧（多渠道引流），副行为 disguise（伪装成正规平台）
    aiBehavior: {
      kind: "flank",
      trigger: { chance: 0.4, cooldown: 2.5 },
      secondary: "disguise",
    },
  },

  // ===== 其他 2026 新型诈骗（3 种） =====
  aiInvestAdvisor: {
    id: "aiInvestAdvisor",
    name: "AI 投顾",
    emoji: "🤖",
    hp: 130,
    speed: 54,
    damage: 22,
    reward: 240,
    color: "#3F51B5",
    fraudType: "AI 智能投顾理财诈骗",
    element: "tech",
    ability: "shield",
    shape: "hexagon",
    isNew: true,
    codexId: "codex_aiInvestAdvisor",
    // v11 AI：间歇伪装成正常 NPC（AI 投顾 APP 看似正规），副行为 enrage
    aiBehavior: {
      kind: "disguise",
      trigger: { chance: 0.35, cooldown: 3.5 },
      params: { disguiseDuration: 2.0 },
      secondary: "enrage",
    },
  },
  aiPhishingSite: {
    id: "aiPhishingSite",
    name: "AI 钓鱼网站",
    emoji: "🕸️",
    hp: 100,
    speed: 68,
    damage: 18,
    reward: 200,
    color: "#009688",
    fraudType: "AI 生成钓鱼网站诈骗",
    element: "tech",
    ability: "speedBoost",
    shape: "hook",
    isNew: true,
    codexId: "codex_aiPhishingSite",
    // v11 AI：低血量群冲，模拟 AI 批量生成钓鱼网站病毒式扩散
    aiBehavior: {
      kind: "rush",
      trigger: { belowHpRatio: 0.4 },
      params: { speedMul: 1.6 },
    },
  },
  aiCustomerService: {
    id: "aiCustomerService",
    name: "AI 合成客服",
    emoji: "📞",
    hp: 115,
    speed: 60,
    damage: 20,
    reward: 220,
    color: "#5C6BC0",
    fraudType: "AI 合成客服语音诈骗",
    element: "emotion",
    ability: "taunt",
    shape: "phone",
    isNew: true,
    codexId: "codex_aiCustomerService",
    // v11 AI：绕侧 + 间歇伪装，模拟 AI 客服多渠道接入+拟人声
    aiBehavior: {
      kind: "flank",
      trigger: { chance: 0.5, cooldown: 2 },
      secondary: "disguise",
    },
  },
};

// ====================================================================
// A2：3 个新 BOSS（F116/F117/F118，三阶段 + 剧情对白）
// F116: AI 实时换脸首脑 · 镜像二代
// F117: 数字人民币授权首脑 · 钱包收割者
// F118: 加密货币杀猪盘首脑 · 屠夫老板
// ====================================================================

export const BOSSES_V11: BossRushDef[] = [
  // F116：AI 实时换脸首脑
  {
    id: "boss_aiFaceSwap",
    name: "镜像二代 · 换脸首脑",
    emoji: "🎞️",
    hp: 1400,
    speed: 32,
    damage: 42,
    reward: 1500,
    color: "#9C27B0",
    fraudType: "AI 实时换脸视频通话首脑",
    scale: 1.8,
    summonTypeId: "aiRealtimeFaceSwap",
    summonInterval: 3.5,
    summonCount: 2,
    summonLane: 1,
    enrageAtHp: 0.4,
    enrageSpeedMul: 1.7,
    enrageDamageMul: 1.5,
    skillName: "实时换脸风暴",
    skillDesc: "每 3.5 秒召唤 2 名 AI 实时换脸 + 间歇隐身规避识别",
    element: "tech",
    shape: "mask",
    isNew: true,
    phases: [
      {
        atHp: 0.6,
        name: "换脸阵列",
        desc: "召唤数 ×2，间歇隐身 1.5 秒",
        effect: "doubleSummon",
        value: 2,
      },
      {
        atHp: 0.3,
        name: "镜像狂暴",
        desc: "速度 ×1.7，伤害 ×1.5，反射 20% 投射物伤害",
        effect: "reflect",
        value: 0.2,
      },
    ],
  },
  // F117：数字人民币授权首脑
  {
    id: "boss_digitalRmb",
    name: "钱包收割者 · 数字人民币首脑",
    emoji: "🪙",
    hp: 1600,
    speed: 28,
    damage: 48,
    reward: 1700,
    color: "#FF6F00",
    fraudType: "数字人民币钱包授权诈骗首脑",
    scale: 1.9,
    summonTypeId: "digitalRmbAuth",
    summonInterval: 3,
    summonCount: 2,
    summonLane: 0,
    enrageAtHp: 0.45,
    enrageSpeedMul: 1.6,
    enrageDamageMul: 1.6,
    skillName: "授权收割",
    skillDesc: "每 3 秒召唤 2 名数字人民币授权 + 首次命中减半",
    element: "money",
    shape: "wallet",
    isNew: true,
    phases: [
      {
        atHp: 0.6,
        name: "授权洪流",
        desc: "召唤间隔 -40%，副召唤 fakeDigitalWallet",
        effect: "doubleSummon",
        value: 0.6,
      },
      {
        atHp: 0.3,
        name: "钱包护盾",
        desc: "获得护盾，每秒回血 1.5%",
        effect: "healSelf",
        value: 0.015,
      },
    ],
  },
  // F118：加密货币杀猪盘首脑
  {
    id: "boss_cryptoPig",
    name: "屠夫老板 · 加密杀猪盘首脑",
    emoji: "🐖",
    hp: 1800,
    speed: 24,
    damage: 52,
    reward: 2000,
    color: "#E91E63",
    fraudType: "加密货币杀猪盘首脑",
    scale: 2.0,
    summonTypeId: "cryptoPigButcher",
    summonInterval: 2.8,
    summonCount: 3,
    summonLane: 2,
    enrageAtHp: 0.5,
    enrageSpeedMul: 1.8,
    enrageDamageMul: 1.7,
    skillName: "杀猪收割",
    skillDesc: "每 2.8 秒召唤 3 名加密杀猪盘 + 治疗光环",
    element: "emotion",
    shape: "heart",
    isNew: true,
    phases: [
      {
        atHp: 0.6,
        name: "情感陷阱",
        desc: "召唤数 ×2，附近敌人每秒回血 12",
        effect: "doubleSummon",
        value: 2,
      },
      {
        atHp: 0.3,
        name: "绝望屠宰",
        desc: "速度 ×1.8，伤害 ×1.7，分裂死亡召唤",
        effect: "split",
      },
    ],
  },
];

// ====================================================================
// A2 配套：3 个新 BOSS 的剧情对白（开战前 + 击破后）
// ====================================================================

export const BOSS_DIALOGUES_V11: BossDialogue[] = [
  {
    bossId: "boss_aiFaceSwap",
    intro: [
      {
        speaker: "镜像二代",
        emoji: "🎞️",
        text: "你以为视频里的人就是真的？我的换脸模型已进化到实时 60 帧。",
        color: "#9C27B0",
        side: "enemy",
      },
      {
        speaker: "沈锋",
        emoji: "🔫",
        text: "再真的换脸也有破绽。倒放、眨眼频率、耳廓轮廓……我们全在盯。",
        color: "#FF7A1A",
        side: "player",
      },
      {
        speaker: "镜像二代",
        emoji: "🎞️",
        text: "那就让你们看看，0.1 秒切换 100 张脸的恐怖。",
        color: "#9C27B0",
        side: "enemy",
      },
    ],
    outro: [
      {
        speaker: "镜像二代",
        emoji: "🎞️",
        text: "不可能……我的模型在 GPU 集群上训练了三个月……",
        color: "#9C27B0",
        side: "enemy",
      },
      {
        speaker: "AI 鉴伪师",
        emoji: "🤖",
        text: "你的换脸在光影一致性上暴露了。AI 鉴伪永远快你一步。",
        color: "#A8E6CF",
        side: "player",
      },
      {
        speaker: "96110",
        emoji: "📞",
        text: "视频通话借钱，务必换渠道电话核实。AI 换脸 ≠ 真人。",
        color: "#1AD670",
        side: "player",
      },
    ],
  },
  {
    bossId: "boss_digitalRmb",
    intro: [
      {
        speaker: "钱包收割者",
        emoji: "🪙",
        text: "数字人民币是国家推动的，授权页面我做得以假乱真。",
        color: "#FF6F00",
        side: "enemy",
      },
      {
        speaker: "法务审计师",
        emoji: "⚖️",
        text: "数字人民币钱包不会通过短信链接索要授权码。你在伪造流程。",
        color: "#3D8BFD",
        side: "player",
      },
      {
        speaker: "钱包收割者",
        emoji: "🪙",
        text: "哼，受害者点的那个'确认'，就是钱进我口袋的开关。",
        color: "#FF6F00",
        side: "enemy",
      },
    ],
    outro: [
      {
        speaker: "钱包收割者",
        emoji: "🪙",
        text: "授权链断了……我的钱包矩阵崩了……",
        color: "#FF6F00",
        side: "enemy",
      },
      {
        speaker: "苏岩",
        emoji: "📊",
        text: "授权链已冻结，受害资金拦截率 87%。剩下 13% 在追。",
        color: "#FFD666",
        side: "player",
      },
      {
        speaker: "96110",
        emoji: "📞",
        text: "数字人民币官方钱包只在指定应用商店下载。授权码绝不外泄。",
        color: "#1AD670",
        side: "player",
      },
    ],
  },
  {
    bossId: "boss_cryptoPig",
    intro: [
      {
        speaker: "屠夫老板",
        emoji: "🐖",
        text: "养猪三年，一刀宰。加密货币的去中心化，就是你们追不回来的死穴。",
        color: "#E91E63",
        side: "enemy",
      },
      {
        speaker: "陈默",
        emoji: "🥷",
        text: "三年潜伏，你的园区地址、资金链、上下线，我全掌握了。",
        color: "#E5353B",
        side: "player",
      },
      {
        speaker: "屠夫老板",
        emoji: "🐖",
        text: "那又如何？加密地址一转再转，跨国执法？做梦！",
        color: "#E91E63",
        side: "enemy",
      },
    ],
    outro: [
      {
        speaker: "屠夫老板",
        emoji: "🐖",
        text: "国际刑警……怎么可能这么快……我的资产被链上冻结了？！",
        color: "#E91E63",
        side: "enemy",
      },
      {
        speaker: "跨境联络官",
        emoji: "🌐",
        text: "链上地址已上灰名单，4 个国家联合冻结。去中心化不等于无法追踪。",
        color: "#FF8A3D",
        side: "player",
      },
      {
        speaker: "96110",
        emoji: "📞",
        text: "加密货币投资认持牌交易所。群里晒单都是托，USDT 不出金是常态。",
        color: "#1AD670",
        side: "player",
      },
    ],
  },
];

// ====================================================================
// A3-1：12 个新敌人的图鉴条目
// ====================================================================

export const CODEX_V11_ENEMY: CodexEntry[] = [
  {
    id: "codex_aiRealtimeFaceSwap",
    category: "enemy",
    name: "AI 实时换脸",
    emoji: "🎞️",
    short: "AI 实时换脸视频通话诈骗",
    detail: "使用实时换脸模型在视频通话中冒充亲友/领导，0.1 秒切换脸，受害人肉眼难辨。",
    tip: "视频通话借钱，让对方用手遮挡半脸或侧脸——换脸模型会瞬间穿帮。",
    unlockHint: "首次击杀 AI 实时换脸",
    refId: "aiRealtimeFaceSwap",
    color: "#9C27B0",
  },
  {
    id: "codex_aiBlackmail",
    category: "enemy",
    name: "AI 换脸敲诈",
    emoji: "😈",
    short: "AI 换脸合成不雅视频敲诈",
    detail: "用受害人公开影像 + AI 换脸合成不雅视频，以发布为由勒索钱财。",
    tip: "收到不雅视频敲诈，直接 110 报案。AI 合成视频可被鉴伪技术识别。",
    unlockHint: "首次击杀 AI 换脸敲诈",
    refId: "aiBlackmail",
    color: "#B71C1C",
  },
  {
    id: "codex_deepfakeVideoCall",
    category: "enemy",
    name: "Deepfake 视频通话",
    emoji: "📹",
    short: "Deepfake 视频通话冒充领导",
    detail: "通过 Deepfake 视频通话冒充领导，要求紧急转账到陌生账户。",
    tip: "领导视频借钱，换渠道（电话/当面）核实。视频里的人 ≠ 领导本人。",
    unlockHint: "首次击杀 Deepfake 视频通话",
    refId: "deepfakeVideoCall",
    color: "#6A1B9A",
  },
  {
    id: "codex_digitalRmbAuth",
    category: "enemy",
    name: "数字人民币授权",
    emoji: "🪙",
    short: "数字人民币钱包授权诈骗",
    detail: "伪造数字人民币授权页面，诱导用户输入授权码，授权后钱包资产被瞬间转走。",
    tip: "数字人民币官方钱包只在指定应用商店下载。授权码绝不外泄。",
    unlockHint: "首次击杀数字人民币授权",
    refId: "digitalRmbAuth",
    color: "#FF6F00",
  },
  {
    id: "codex_fakeDigitalWallet",
    category: "enemy",
    name: "虚假数字钱包",
    emoji: "👛",
    short: "虚假数字货币钱包 APP 诈骗",
    detail: "伪造数字货币钱包 APP，前期可小额提现，大额充值后 APP 跑路。",
    tip: "数字货币钱包认官方/持牌交易所。'高额返利'是骗局前奏。",
    unlockHint: "首次击杀虚假数字钱包",
    refId: "fakeDigitalWallet",
    color: "#F57C00",
  },
  {
    id: "codex_fakeSmartContract",
    category: "enemy",
    name: "虚假智能合约",
    emoji: "📜",
    short: "虚假智能合约授权诈骗",
    detail: "诱导用户点击'空投领取'等链接，签名授权后合约自动转走钱包所有资产。",
    tip: "智能合约授权需谨慎。'无限授权'等于交出钱包控制权。",
    unlockHint: "首次击杀虚假智能合约",
    refId: "fakeSmartContract",
    color: "#FBC02D",
  },
  {
    id: "codex_cryptoPigButcher",
    category: "enemy",
    name: "加密杀猪盘",
    emoji: "🐖",
    short: "加密货币杀猪盘诈骗",
    detail: "网恋建立情感后引导投资加密货币，'养猪'数月后'杀猪'收割，资金一去不回。",
    tip: "网恋 + 加密货币投资 = 100% 杀猪盘。群里晒单都是托。",
    unlockHint: "首次击杀加密杀猪盘",
    refId: "cryptoPigButcher",
    color: "#E91E63",
  },
  {
    id: "codex_nftAirdropPhish",
    category: "enemy",
    name: "NFT 空投钓鱼",
    emoji: "🖼️",
    short: "NFT 空投钓鱼链接诈骗",
    detail: "通过虚假 NFT 空投链接诱导用户签名授权，授权后钱包 NFT 与代币被瞬间转走。",
    tip: "NFT 空投认官方渠道。陌生链接签名前用 revoke.cash 检查授权。",
    unlockHint: "首次击杀 NFT 空投钓鱼",
    refId: "nftAirdropPhish",
    color: "#00BCD4",
  },
  {
    id: "codex_metaverseLand",
    category: "enemy",
    name: "元宇宙土地",
    emoji: "🌌",
    short: "元宇宙虚拟土地诈骗",
    detail: "以'元宇宙土地抢购'为名，发行虚假虚拟土地 NFT，炒作升值后跑路。",
    tip: "元宇宙土地无统一估值标准。'保本升值'是骗局话术。",
    unlockHint: "首次击杀元宇宙土地",
    refId: "metaverseLand",
    color: "#7C4DFF",
  },
  {
    id: "codex_aiInvestAdvisor",
    category: "enemy",
    name: "AI 投顾",
    emoji: "🤖",
    short: "AI 智能投顾理财诈骗",
    detail: "伪装'AI 智能投顾'APP，号称 AI 选股保本高收益，实际是庞氏骗局。",
    tip: "AI 投顾认持牌机构。证监会官网可查投资咨询资质。",
    unlockHint: "首次击杀 AI 投顾",
    refId: "aiInvestAdvisor",
    color: "#3F51B5",
  },
  {
    id: "codex_aiPhishingSite",
    category: "enemy",
    name: "AI 钓鱼网站",
    emoji: "🕸️",
    short: "AI 生成钓鱼网站诈骗",
    detail: "用 AI 批量生成高度仿真的钓鱼网站（银行/政务/电商），规避关键词检测。",
    tip: "网址认官方。浏览器地址栏的 SSL 锁 ≠ 真实性，要看域名拼写。",
    unlockHint: "首次击杀 AI 钓鱼网站",
    refId: "aiPhishingSite",
    color: "#009688",
  },
  {
    id: "codex_aiCustomerService",
    category: "enemy",
    name: "AI 合成客服",
    emoji: "📞",
    short: "AI 合成客服语音诈骗",
    detail: "用 AI 合成客服声音 + 撞库订单信息，诱导受害人共享屏幕后转走资金。",
    tip: "客服不主动。AI 声音可合成，订单信息可撞库，唯官方 APP 可信。",
    unlockHint: "首次击杀 AI 合成客服",
    refId: "aiCustomerService",
    color: "#5C6BC0",
  },
];

// ====================================================================
// A3-2：3 个新 BOSS 的图鉴条目
// ====================================================================

export const CODEX_V11_CASE: CodexEntry[] = [
  {
    id: "codex_case_aiFaceSwap",
    category: "case",
    name: "镜像二代 · 实时换脸案",
    emoji: "🎞️",
    short: "AI 实时换脸视频通话首脑案",
    detail: "镜像二代团伙使用实时换脸模型，3 个月内冒充亲友视频通话诈骗 47 起，涉案 1200 万。",
    tip: "视频通话借钱，让对方做特定动作（遮挡/侧脸）核实，换脸模型会穿帮。",
    unlockHint: "击破 BOSS 镜像二代",
    refId: "boss_aiFaceSwap",
    color: "#9C27B0",
  },
  {
    id: "codex_case_digitalRmb",
    category: "case",
    name: "钱包收割者 · 数字人民币案",
    emoji: "🪙",
    short: "数字人民币授权诈骗首脑案",
    detail: "钱包收割者团伙伪造数字人民币授权页面，6 个月内骗转 2300 万，受害人 800+。",
    tip: "数字人民币授权码绝不外泄。官方钱包只在指定应用商店下载。",
    unlockHint: "击破 BOSS 钱包收割者",
    refId: "boss_digitalRmb",
    color: "#FF6F00",
  },
  {
    id: "codex_case_cryptoPig",
    category: "case",
    name: "屠夫老板 · 加密杀猪盘案",
    emoji: "🐖",
    short: "加密货币杀猪盘首脑案",
    detail: "屠夫老板团伙伪装优质异性形象，2 年内骗取 300+ 受害人共 6800 万，跨境联合执法清零。",
    tip: "网恋 + 加密货币投资 = 100% 杀猪盘。USDT 不出金是常见跑路前兆。",
    unlockHint: "击破 BOSS 屠夫老板",
    refId: "boss_cryptoPig",
    color: "#E91E63",
  },
];

// ====================================================================
// A3-3：3 个新 BOSS 对应的真实案例（脱敏处理）
// ====================================================================

export const REAL_CASES_V11: RealCaseDef[] = [
  {
    id: "case_aiFaceSwap",
    refEnemyId: "boss_aiFaceSwap",
    title: "实时换脸视频诈骗案",
    year: "2026",
    summary: "某诈骗团伙使用开源实时换脸模型，通过视频通话冒充亲友，3 个月作案 47 起，单人最高被骗 80 万。警方联合 AI 鉴伪实验室跨境执法捣毁窝点。",
    amount: 12000000,
    victim: "中老年群体 + 海外留学生",
    bustedBy: "公安部反诈中心 + AI 鉴伪实验室",
    tip: "视频通话借钱，让对方用手遮挡半脸——换脸模型会瞬间穿帮。",
    hotline: "96110 反诈专线，AI 换脸诈骗请立即举报并提供视频证据。",
    color: "#9C27B0",
    emoji: "🎞️",
  },
  {
    id: "case_digitalRmb",
    refEnemyId: "boss_digitalRmb",
    title: "数字人民币授权诈骗案",
    year: "2026",
    summary: "犯罪团伙伪造数字人民币授权页面，通过短信链接诱导用户输入授权码，6 个月内骗转 2300 万。受害人多为数字人民币新用户。",
    amount: 23000000,
    victim: "数字人民币新用户",
    bustedBy: "央行数字货币研究所 + 公安部",
    tip: "数字人民币授权码 = 钱包控制权。绝不通过短信链接输入。",
    hotline: "96110 提醒：数字人民币官方钱包只在指定应用商店下载。",
    color: "#FF6F00",
    emoji: "🪙",
  },
  {
    id: "case_cryptoPig",
    refEnemyId: "boss_cryptoPig",
    title: "加密货币杀猪盘案",
    year: "2026",
    summary: "跨境诈骗团伙伪装优质异性形象，通过社交平台'养猪'数月后引导投资加密货币，2 年内骗取 300+ 受害人共 6800 万。多国联合执法清零园区。",
    amount: 68000000,
    victim: "单身白领 + 退休人员",
    bustedBy: "国际刑警组织 + 公安部跨境联合执法",
    tip: "网恋 + 加密货币投资 = 100% 杀猪盘。USDT 不出金是跑路前兆。",
    hotline: "96110 反诈专线，加密货币诈骗可申请链上资金冻结。",
    color: "#E91E63",
    emoji: "🐖",
  },
];

// ====================================================================
// A3-4：3 个新 BOSS 对应的案例五步复盘（兼容 v9 分支式调查）
// ====================================================================

export const CASE_BREAKDOWNS_V11: CaseBreakdownDef[] = [
  {
    caseId: "case_aiFaceSwap",
    title: "AI 实时换脸视频诈骗案 · 五步复盘",
    correctInterceptIdx: 1,
    steps: [
      {
        order: 1,
        name: "接触",
        desc: "受害人接到陌生视频通话，对方面容与亲友完全一致。",
        warningSign: "陌生号码发起视频通话",
        correctAction: "挂断后用通讯录中保存的号码回拨核实",
      },
      {
        order: 2,
        name: "信任",
        desc: "对方用亲友口吻寒暄，提及共同回忆，受害人放下戒备。",
        warningSign: "视频画面偶有闪烁/眨眼频率异常",
        correctAction: "要求对方做特定动作（遮挡半脸/侧脸/快速转头）",
      },
      {
        order: 3,
        name: "诱导",
        desc: "对方以'急需周转''手术费'等理由要求转账。",
        warningSign: "紧急感强 + 金额较大 + 陌生账户",
        correctAction: "换渠道（电话/当面）核实，金额大时延迟 24 小时",
      },
      {
        order: 4,
        name: "转账",
        desc: "对方提供陌生账户，催促'快转，不然来不及'。",
        warningSign: "陌生账户 + 催促 + 不让挂断",
        correctAction: "立即挂断，拨打 96110 或 110 报案",
      },
      {
        order: 5,
        name: "拉黑",
        desc: "转账后视频挂断，对方失联。",
        warningSign: "转账后失联",
        correctAction: "立即报案，提供视频证据 + 转账记录",
      },
    ],
    reward: { score: 1500, antiFraudPoints: 80 },
    investigation: {
      startNodeId: "node_1",
      nodes: [
        {
          id: "node_1",
          title: "第一阶段：视频通话来源调查",
          scene: "受害人接到 +86 1XX XXXX XXXX 来电，对方视频面容与儿子完全一致，称'妈，我出事了，急需 8 万'。",
          choices: [
            {
              text: "立即挂断，用通讯录中保存的儿子号码回拨",
              emoji: "📞",
              verdict: "perfect",
              feedback: "最佳拦截。换渠道核实是识破换脸的第一步。",
              nextNodeId: "node_2",
              evidenceDelta: 30,
              lossDelta: 0,
            },
            {
              text: "继续通话，要求对方说出儿子的生日",
              emoji: "🎂",
              verdict: "ok",
              feedback: "正确方向，但 AI 已能从社交数据中提取生日，风险仍在。",
              nextNodeId: "node_2",
              evidenceDelta: 15,
              lossDelta: 5,
            },
            {
              text: "完全相信视频，按对方要求转账",
              emoji: "💸",
              verdict: "wrong",
              feedback: "致命错误。视频面容 ≠ 真人，必须换渠道核实。",
              nextNodeId: "node_2",
              evidenceDelta: 0,
              lossDelta: 50,
            },
          ],
        },
        {
          id: "node_2",
          title: "第二阶段：换脸破绽鉴定",
          scene: "通话中对方催促转账，但画面偶有闪烁，眨眼频率异常。",
          choices: [
            {
              text: "要求对方用手遮挡半脸 3 秒",
              emoji: "🖐️",
              verdict: "perfect",
              feedback: "最佳鉴伪。换脸模型在遮挡/侧脸时会瞬间穿帮。",
              nextNodeId: "node_3",
              evidenceDelta: 30,
              lossDelta: 0,
            },
            {
              text: "要求对方快速转头 90 度",
              emoji: "🔄",
              verdict: "ok",
              feedback: "正确方向，但部分换脸模型已能处理转头。",
              nextNodeId: "node_3",
              evidenceDelta: 20,
              lossDelta: 5,
            },
            {
              text: "忽视画面闪烁，继续相信",
              emoji: "🙈",
              verdict: "wrong",
              feedback: "致命错误。闪烁/眨眼异常是换脸的核心破绽。",
              nextNodeId: "node_3",
              evidenceDelta: 0,
              lossDelta: 40,
            },
          ],
        },
        {
          id: "node_3",
          title: "第三阶段：拦截决策",
          scene: "确认是 AI 换脸后，对方仍在持续来电施压。",
          choices: [
            {
              text: "立即报案 + 提供视频证据 + 通知通讯录亲友",
              emoji: "🚔",
              verdict: "perfect",
              feedback: "最佳应对。报案 + 证据保全 + 预警扩散三管齐下。",
              nextNodeId: null,
              evidenceDelta: 40,
              lossDelta: 0,
            },
            {
              text: "拉黑号码，不报案",
              emoji: "🚫",
              verdict: "warn",
              feedback: "方向正确但放弃追赃。报案可启动链上资金冻结。",
              nextNodeId: null,
              evidenceDelta: 10,
              lossDelta: 20,
            },
          ],
        },
      ],
      endings: [
        {
          id: "ending_s",
          rank: "S",
          title: "完美拦截 · 链上冻结",
          desc: "受害人换渠道核实识破换脸，报案后链上资金冻结率 95%。",
          minEvidence: 90,
          maxLoss: 5,
          rewardMul: 1.5,
          legalCharacterization: "诈骗罪（数额特别巨大），3 年以上 10 年以下有期徒刑。",
          hotline: "96110 反诈专线，AI 换脸诈骗请立即举报。",
        },
        {
          id: "ending_a",
          rank: "A",
          title: "成功拦截 · 部分追赃",
          desc: "受害人通过鉴伪识破换脸，报案后追回 60% 资金。",
          minEvidence: 60,
          maxLoss: 30,
          rewardMul: 1.2,
          legalCharacterization: "诈骗罪（数额巨大），3 年以上 10 年以下有期徒刑。",
          hotline: "96110 反诈专线，AI 换脸诈骗请立即举报。",
        },
        {
          id: "ending_b",
          rank: "B",
          title: "止损 · 部分损失",
          desc: "受害人在转账前识破，但已泄露部分信息。",
          minEvidence: 30,
          maxLoss: 60,
          rewardMul: 1.0,
          legalCharacterization: "诈骗未遂，可减轻处罚。",
          hotline: "96110 反诈专线，及时止损是关键。",
        },
        {
          id: "ending_c",
          rank: "C",
          title: "受骗 · 全额损失",
          desc: "受害人完全相信换脸，转账后失联才察觉被骗。",
          minEvidence: 0,
          maxLoss: 100,
          rewardMul: 0.5,
          legalCharacterization: "诈骗罪（数额特别巨大），3 年以上 10 年以下有期徒刑。",
          hotline: "96110 反诈专线，AI 换脸诈骗请立即举报。",
        },
      ],
    },
  },
  {
    caseId: "case_digitalRmb",
    title: "数字人民币授权诈骗案 · 五步复盘",
    correctInterceptIdx: 2,
    steps: [
      {
        order: 1,
        name: "接触",
        desc: "受害人收到'数字人民币钱包异常'短信，含伪造官方链接。",
        warningSign: "陌生短信号码 + 含链接",
        correctAction: "不点击短信链接，通过官方 APP 核实",
      },
      {
        order: 2,
        name: "信任",
        desc: "链接打开后页面与官方页面高度相似，含数字人民币 LOGO。",
        warningSign: "页面要求输入授权码",
        correctAction: "立即关闭，授权码绝不外泄",
      },
      {
        order: 3,
        name: "诱导",
        desc: "页面提示'不授权将影响征信'，制造紧迫感。",
        warningSign: "威胁征信 + 紧迫感",
        correctAction: "征信只能本人到央行或官方渠道查询",
      },
      {
        order: 4,
        name: "转账",
        desc: "用户输入授权码后，钱包资产被瞬间转走。",
        warningSign: "授权后资产立即减少",
        correctAction: "立即报案，申请链上冻结",
      },
      {
        order: 5,
        name: "拉黑",
        desc: "页面失联，短信被删除。",
        warningSign: "证据被删除",
        correctAction: "通过银行流水 + 短信截图报案",
      },
    ],
    reward: { score: 1700, antiFraudPoints: 90 },
    investigation: {
      startNodeId: "node_1",
      nodes: [
        {
          id: "node_1",
          title: "第一阶段：短信来源核实",
          scene: "受害人收到'【数字人民币】您的钱包异常，请点击 http://dcep-x.cf 核实'短信。",
          choices: [
            {
              text: "不点击链接，打开手机银行 APP 自助核实",
              emoji: "🏦",
              verdict: "perfect",
              feedback: "最佳拦截。官方 APP 是唯一可信核实渠道。",
              nextNodeId: "node_2",
              evidenceDelta: 35,
              lossDelta: 0,
            },
            {
              text: "点击链接查看，但不输入任何信息",
              emoji: "👀",
              verdict: "warn",
              feedback: "有风险。钓鱼网站可能利用 JS 漏洞窃取信息。",
              nextNodeId: "node_2",
              evidenceDelta: 10,
              lossDelta: 10,
            },
            {
              text: "完全相信短信，按页面提示输入授权码",
              emoji: "🔐",
              verdict: "wrong",
              feedback: "致命错误。授权码 = 钱包控制权，绝不外泄。",
              nextNodeId: "node_2",
              evidenceDelta: 0,
              lossDelta: 60,
            },
          ],
        },
        {
          id: "node_2",
          title: "第二阶段：授权请求识别",
          scene: "页面提示'为完成核实，请输入数字人民币授权码'，并威胁'不授权将影响征信'。",
          choices: [
            {
              text: "立即关闭页面，拨打 96110 举报",
              emoji: "📞",
              verdict: "perfect",
              feedback: "最佳应对。识别威胁话术 + 主动举报。",
              nextNodeId: "node_3",
              evidenceDelta: 35,
              lossDelta: 0,
            },
            {
              text: "查询央行征信官方渠道",
              emoji: "🏛️",
              verdict: "ok",
              feedback: "正确方向。征信只能本人到央行或官方渠道查询。",
              nextNodeId: "node_3",
              evidenceDelta: 25,
              lossDelta: 5,
            },
            {
              text: "因害怕影响征信，输入授权码",
              emoji: "😰",
              verdict: "wrong",
              feedback: "致命错误。'影响征信'是经典恐吓话术，授权码一旦泄露资产即失。",
              nextNodeId: "node_3",
              evidenceDelta: 0,
              lossDelta: 50,
            },
          ],
        },
        {
          id: "node_3",
          title: "第三阶段：资金冻结决策",
          scene: "确认是钓鱼网站后，需要决定后续动作。",
          choices: [
            {
              text: "立即报案 + 银行流水 + 短信截图保全证据",
              emoji: "🚔",
              verdict: "perfect",
              feedback: "最佳应对。报案 + 证据保全可启动链上资金冻结。",
              nextNodeId: null,
              evidenceDelta: 30,
              lossDelta: 0,
            },
            {
              text: "删除短信，不予理会",
              emoji: "🗑️",
              verdict: "warn",
              feedback: "止损但放弃追赃，且无预警扩散。",
              nextNodeId: null,
              evidenceDelta: 5,
              lossDelta: 15,
            },
          ],
        },
      ],
      endings: [
        {
          id: "ending_s",
          rank: "S",
          title: "完美拦截 · 链上冻结",
          desc: "受害人通过官方 APP 核实识破钓鱼，报案后链上资金冻结率 95%。",
          minEvidence: 90,
          maxLoss: 5,
          rewardMul: 1.5,
          legalCharacterization: "诈骗罪（数额特别巨大），3 年以上 10 年以下有期徒刑。",
          hotline: "96110 反诈专线，数字人民币诈骗请立即举报。",
        },
        {
          id: "ending_a",
          rank: "A",
          title: "成功拦截 · 部分追赃",
          desc: "受害人识别威胁话术后止损，报案追回 60% 资金。",
          minEvidence: 60,
          maxLoss: 30,
          rewardMul: 1.2,
          legalCharacterization: "诈骗罪（数额巨大），3 年以上 10 年以下有期徒刑。",
          hotline: "96110 反诈专线，数字人民币诈骗请立即举报。",
        },
        {
          id: "ending_b",
          rank: "B",
          title: "止损 · 信息泄露",
          desc: "受害人点击链接但未输入授权码，已泄露部分信息。",
          minEvidence: 30,
          maxLoss: 60,
          rewardMul: 1.0,
          legalCharacterization: "诈骗未遂，可减轻处罚。",
          hotline: "96110 反诈专线，及时修改钱包密码。",
        },
        {
          id: "ending_c",
          rank: "C",
          title: "受骗 · 全额损失",
          desc: "受害人输入授权码，钱包资产被瞬间转走。",
          minEvidence: 0,
          maxLoss: 100,
          rewardMul: 0.5,
          legalCharacterization: "诈骗罪（数额特别巨大），3 年以上 10 年以下有期徒刑。",
          hotline: "96110 反诈专线，立即报案申请链上冻结。",
        },
      ],
    },
  },
  {
    caseId: "case_cryptoPig",
    title: "加密货币杀猪盘案 · 五步复盘",
    correctInterceptIdx: 0,
    steps: [
      {
        order: 1,
        name: "接触",
        desc: "受害人在社交平台收到优质异性'误加好友'消息。",
        warningSign: "陌生异性主动 + 头像精致",
        correctAction: "不回应，直接拉黑",
      },
      {
        order: 2,
        name: "信任",
        desc: "对方每日嘘寒问暖，分享'投资收益截图'，建立情感。",
        warningSign: "投资收益截图 + 持续情感投入",
        correctAction: "警惕'网恋+投资'组合，必是杀猪盘",
      },
      {
        order: 3,
        name: "诱导",
        desc: "对方引导下载陌生 APP，称'内部通道，稳赚不赔'。",
        warningSign: "陌生 APP + 稳赚承诺",
        correctAction: "不下载陌生 APP，认持牌交易所",
      },
      {
        order: 4,
        name: "转账",
        desc: "前期小额提现建立信任，受害人投入大额资金。",
        warningSign: "前期可提现 + 后期大额",
        correctAction: "立即提现 + 报案",
      },
      {
        order: 5,
        name: "拉黑",
        desc: "大额投入后 APP 跑路，对方失联。",
        warningSign: "APP 无法登录 + 对方失联",
        correctAction: "立即报案，提供链上地址",
      },
    ],
    reward: { score: 2000, antiFraudPoints: 100 },
    investigation: {
      startNodeId: "node_1",
      nodes: [
        {
          id: "node_1",
          title: "第一阶段：社交接触识别",
          scene: "受害人在社交平台收到'嗨，我加错人了，但觉得你很有气质'的消息，对方头像是精致女性。",
          choices: [
            {
              text: "不回应，直接拉黑",
              emoji: "🚫",
              verdict: "perfect",
              feedback: "最佳拦截。陌生异性主动搭讪 + 精致头像 = 杀猪盘典型特征。",
              nextNodeId: "node_2",
              evidenceDelta: 35,
              lossDelta: 0,
            },
            {
              text: "回应但保持警惕，不谈感情",
              emoji: "🤔",
              verdict: "ok",
              feedback: "方向正确但风险仍在，杀猪盘擅长长期渗透。",
              nextNodeId: "node_2",
              evidenceDelta: 15,
              lossDelta: 10,
            },
            {
              text: "积极回应，开始情感交流",
              emoji: "💕",
              verdict: "wrong",
              feedback: "致命错误。这正是'养猪'阶段，情感投入越深损失越大。",
              nextNodeId: "node_2",
              evidenceDelta: 0,
              lossDelta: 40,
            },
          ],
        },
        {
          id: "node_2",
          title: "第二阶段：投资话术识别",
          scene: "对方每日嘘寒问暖后，'不经意'提及'我表哥在币圈内部消息，上周赚了 30 万'，并分享截图。",
          choices: [
            {
              text: "立即识别杀猪盘，拉黑 + 举报",
              emoji: "🚨",
              verdict: "perfect",
              feedback: "最佳拦截。'网恋+投资'是杀猪盘铁证。",
              nextNodeId: "node_3",
              evidenceDelta: 35,
              lossDelta: 0,
            },
            {
              text: "表示对投资不感兴趣，但继续聊天",
              emoji: "🙅",
              verdict: "warn",
              feedback: "止损但不彻底，对方会换话术继续渗透。",
              nextNodeId: "node_3",
              evidenceDelta: 10,
              lossDelta: 15,
            },
            {
              text: "感兴趣，询问如何参与",
              emoji: "💰",
              verdict: "wrong",
              feedback: "致命错误。'内部消息''稳赚不赔'是杀猪盘核心话术。",
              nextNodeId: "node_3",
              evidenceDelta: 0,
              lossDelta: 50,
            },
          ],
        },
        {
          id: "node_3",
          title: "第三阶段：资金拦截决策",
          scene: "对方引导下载陌生 APP，前期小额提现成功，要求投入 50 万'大单'。",
          choices: [
            {
              text: "立即提现所有资金 + 拉黑 + 报案",
              emoji: "🏃",
              verdict: "perfect",
              feedback: "最佳应对。前期可提现是诱饵，立即撤退是唯一正确选择。",
              nextNodeId: null,
              evidenceDelta: 30,
              lossDelta: 0,
            },
            {
              text: "继续观望，再投入 5 万试水",
              emoji: "🤞",
              verdict: "wrong",
              feedback: "致命错误。'试水'只会让沉没成本加深，最终全损。",
              nextNodeId: null,
              evidenceDelta: 0,
              lossDelta: 50,
            },
          ],
        },
      ],
      endings: [
        {
          id: "ending_s",
          rank: "S",
          title: "完美拦截 · 链上冻结",
          desc: "受害人在接触阶段识破杀猪盘，报案后团伙被端，链上资金冻结率 95%。",
          minEvidence: 90,
          maxLoss: 5,
          rewardMul: 1.5,
          legalCharacterization: "诈骗罪（数额特别巨大），3 年以上 10 年以下有期徒刑。",
          hotline: "96110 反诈专线，加密货币诈骗可申请链上资金冻结。",
        },
        {
          id: "ending_a",
          rank: "A",
          title: "成功拦截 · 部分追赃",
          desc: "受害人在投资阶段识破，报案追回 60% 资金。",
          minEvidence: 60,
          maxLoss: 30,
          rewardMul: 1.2,
          legalCharacterization: "诈骗罪（数额巨大），3 年以上 10 年以下有期徒刑。",
          hotline: "96110 反诈专线，加密货币诈骗可申请链上资金冻结。",
        },
        {
          id: "ending_b",
          rank: "B",
          title: "止损 · 沉没成本",
          desc: "受害人小额投入后识破，损失前期投入。",
          minEvidence: 30,
          maxLoss: 60,
          rewardMul: 1.0,
          legalCharacterization: "诈骗罪（数额较大），3 年以下有期徒刑。",
          hotline: "96110 反诈专线，及时止损是关键。",
        },
        {
          id: "ending_c",
          rank: "C",
          title: "受骗 · 全额损失",
          desc: "受害人投入大额资金后 APP 跑路，对方失联。",
          minEvidence: 0,
          maxLoss: 100,
          rewardMul: 0.5,
          legalCharacterization: "诈骗罪（数额特别巨大），3 年以上 10 年以下有期徒刑。",
          hotline: "96110 反诈专线，立即报案提供链上地址。",
        },
      ],
    },
  },
];

// ====================================================================
// C2：6 个受害者视角剧本（多结局 + 弱点情报奖励）
// 玩家代入受害人第一人称视角，在每个节点选择应对，多结局
// 通关后解锁弱点情报，塔防中对该类型敌人 +20% 伤害
// ====================================================================

export const VICTIM_SIM_SCENARIOS_V11: VictimSimScenario[] = [
  // 剧本 1：AI 实时换脸冒充亲友
  {
    id: "vsim_aiFaceSwap",
    typeId: "aiRealtimeFaceSwap",
    typeName: "AI 实时换脸诈骗",
    title: "妈，我出事了",
    victimProfile: "独居老人",
    difficulty: 3,
    scenario: "你是 65 岁的退休教师，独居。晚上 8 点，你接到一个视频通话，对方面容与儿子完全一致……",
    startNodeId: "node_1",
    nodes: [
      {
        id: "node_1",
        title: "第一阶段：陌生来电",
        scene: "电话响起，屏幕上显示陌生号码，但接通后视频里是儿子的脸，声音也像。'妈，我手机掉了，借同事电话打的。我出事了，急需 8 万。'",
        scammerLine: "妈，我手机掉了，借同事电话打的。我出事了，急需 8 万周转，你先转过来，明天还你。",
        psychology: ["冒充熟人", "制造紧迫感", "情感操纵"],
        redFlag: 4,
        choices: [
          {
            text: "立即挂断，用通讯录中保存的儿子号码回拨",
            emoji: "📞",
            verdict: "perfect",
            feedback: "最佳应对。换渠道核实是识破换脸的第一步。",
            nextNodeId: "node_2",
            awarenessDelta: 30,
            lossDelta: 0,
          },
          {
            text: "继续通话，问儿子生日核实",
            emoji: "🎂",
            verdict: "ok",
            feedback: "方向正确，但 AI 已能从社交数据提取生日，风险仍在。",
            nextNodeId: "node_2",
            awarenessDelta: 15,
            lossDelta: 10,
          },
          {
            text: "完全相信视频，按对方要求转账",
            emoji: "💸",
            verdict: "wrong",
            feedback: "致命错误。视频面容 ≠ 真人，必须换渠道核实。",
            nextNodeId: "node_2",
            awarenessDelta: 0,
            lossDelta: 60,
          },
        ],
      },
      {
        id: "node_2",
        title: "第二阶段：换脸破绽",
        scene: "无论上一步如何，对方继续施压。视频画面偶有闪烁，眨眼频率异常。",
        scammerLine: "妈，快点啊，那边等着呢，再不转就来不及了！",
        psychology: ["催促", "时间压力"],
        redFlag: 5,
        choices: [
          {
            text: "要求对方用手遮挡半脸 3 秒",
            emoji: "🖐️",
            verdict: "perfect",
            feedback: "最佳鉴伪。换脸模型在遮挡/侧脸时会瞬间穿帮。",
            nextNodeId: "node_3",
            awarenessDelta: 30,
            lossDelta: 0,
          },
          {
            text: "要求对方快速转头 90 度",
            emoji: "🔄",
            verdict: "ok",
            feedback: "正确方向，但部分换脸模型已能处理转头。",
            nextNodeId: "node_3",
            awarenessDelta: 20,
            lossDelta: 5,
          },
          {
            text: "忽视画面闪烁，继续相信",
            emoji: "🙈",
            verdict: "wrong",
            feedback: "致命错误。闪烁/眨眼异常是换脸的核心破绽。",
            nextNodeId: "node_3",
            awarenessDelta: 0,
            lossDelta: 40,
          },
        ],
      },
      {
        id: "node_3",
        title: "第三阶段：拦截决策",
        scene: "已确认对方是 AI 换脸。对方仍在持续来电施压，并威胁'不转就让你儿子坐牢'。",
        scammerLine: "你不转是吧？信不信我让你儿子坐牢！",
        psychology: ["恐吓", "冒充公检法"],
        redFlag: 5,
        choices: [
          {
            text: "立即报案 + 通知通讯录亲友预警",
            emoji: "🚔",
            verdict: "perfect",
            feedback: "最佳应对。报案 + 亲友预警可避免更多人受骗。",
            nextNodeId: null,
            awarenessDelta: 40,
            lossDelta: 0,
          },
          {
            text: "拉黑号码，不报案",
            emoji: "🚫",
            verdict: "warn",
            feedback: "止损但放弃追赃，也未预警扩散。",
            nextNodeId: null,
            awarenessDelta: 10,
            lossDelta: 20,
          },
        ],
      },
    ],
    endings: [
      {
        id: "ending_s",
        rank: "S",
        kind: "rescued",
        title: "完美识破 · 守护亲友",
        desc: "你换渠道核实识破换脸，报案后团伙被端，通讯录亲友零损失。",
        minAwareness: 90,
        maxLoss: 5,
        weaknessIntel: {
          enemyTypeId: "aiRealtimeFaceSwap",
          damageBonus: 0.2,
          desc: "换脸模型在遮挡/侧脸时穿帮，塔防中对该敌人 +20% 伤害",
        },
        hotline: "96110 反诈专线，AI 换脸诈骗请立即举报并提供视频证据。",
      },
      {
        id: "ending_a",
        rank: "A",
        kind: "rescued",
        title: "成功识破 · 部分预警",
        desc: "你识破换脸并报案，但部分亲友已接到类似电话。",
        minAwareness: 60,
        maxLoss: 30,
        weaknessIntel: {
          enemyTypeId: "aiRealtimeFaceSwap",
          damageBonus: 0.15,
          desc: "换脸模型存在破绽，塔防中对该敌人 +15% 伤害",
        },
        hotline: "96110 反诈专线，及时通知亲友预警。",
      },
      {
        id: "ending_b",
        rank: "B",
        kind: "partialLoss",
        title: "止损 · 信息泄露",
        desc: "你在转账前识破，但已泄露部分信息。",
        minAwareness: 30,
        maxLoss: 60,
        hotline: "96110 反诈专线，及时修改个人信息。",
      },
      {
        id: "ending_c",
        rank: "C",
        kind: "totalLoss",
        title: "受骗 · 全额损失",
        desc: "你完全相信换脸，转账后失联才察觉被骗。",
        minAwareness: 0,
        maxLoss: 100,
        hotline: "96110 反诈专线，立即报案申请链上冻结。",
      },
    ],
    takeaways: [
      "视频通话借钱，必须换渠道（电话/当面）核实",
      "AI 换脸在遮挡/侧脸/快速转头时会穿帮",
      "陌生号码 + 紧急借钱 = 高风险信号",
      "96110 是反诈专线，可信赖",
    ],
  },

  // 剧本 2：数字人民币授权诈骗
  {
    id: "vsim_digitalRmb",
    typeId: "digitalRmbAuth",
    typeName: "数字人民币授权诈骗",
    title: "您的钱包异常",
    victimProfile: "数字人民币新用户",
    difficulty: 2,
    scenario: "你是 35 岁的白领，刚开通数字人民币钱包。下午收到一条'钱包异常'短信……",
    startNodeId: "node_1",
    nodes: [
      {
        id: "node_1",
        title: "第一阶段：短信核实",
        scene: "手机震动，短信：'【数字人民币】您的钱包异常，请点击 http://dcep-x.cf 核实，逾期将冻结账户。'",
        scammerLine: "您的钱包异常，请点击链接核实，逾期将冻结账户。",
        psychology: ["冒充官方", "制造紧迫感", "威胁冻结"],
        redFlag: 4,
        choices: [
          {
            text: "不点击链接，打开手机银行 APP 自助核实",
            emoji: "🏦",
            verdict: "perfect",
            feedback: "最佳拦截。官方 APP 是唯一可信核实渠道。",
            nextNodeId: "node_2",
            awarenessDelta: 35,
            lossDelta: 0,
          },
          {
            text: "点击链接查看，但不输入任何信息",
            emoji: "👀",
            verdict: "warn",
            feedback: "有风险。钓鱼网站可能利用 JS 漏洞窃取信息。",
            nextNodeId: "node_2",
            awarenessDelta: 10,
            lossDelta: 15,
          },
          {
            text: "完全相信短信，按页面提示操作",
            emoji: "📲",
            verdict: "wrong",
            feedback: "致命错误。短信链接是钓鱼网站经典入口。",
            nextNodeId: "node_2",
            awarenessDelta: 0,
            lossDelta: 50,
          },
        ],
      },
      {
        id: "node_2",
        title: "第二阶段：授权请求识别",
        scene: "页面与官方页面高度相似，含数字人民币 LOGO，提示'为完成核实，请输入授权码'，并威胁'不授权将影响征信'。",
        scammerLine: "请输入授权码完成核实。不授权将影响您的征信记录。",
        psychology: ["威胁征信", "伪造流程", "冒充官方"],
        redFlag: 5,
        choices: [
          {
            text: "立即关闭页面，拨打 96110 举报",
            emoji: "📞",
            verdict: "perfect",
            feedback: "最佳应对。识别威胁话术 + 主动举报。",
            nextNodeId: "node_3",
            awarenessDelta: 35,
            lossDelta: 0,
          },
          {
            text: "查询央行征信官方渠道",
            emoji: "🏛️",
            verdict: "ok",
            feedback: "正确方向。征信只能本人到央行或官方渠道查询。",
            nextNodeId: "node_3",
            awarenessDelta: 25,
            lossDelta: 5,
          },
          {
            text: "因害怕影响征信，输入授权码",
            emoji: "😰",
            verdict: "wrong",
            feedback: "致命错误。授权码 = 钱包控制权，一旦泄露资产即失。",
            nextNodeId: "node_3",
            awarenessDelta: 0,
            lossDelta: 60,
          },
        ],
      },
      {
        id: "node_3",
        title: "第三阶段：证据保全",
        scene: "已识别是钓鱼网站。需要决定后续动作。",
        scammerLine: "（对方已无法联系，短信被自动删除）",
        psychology: ["毁灭证据"],
        redFlag: 3,
        choices: [
          {
            text: "截图短信 + 银行流水 + 立即报案",
            emoji: "📸",
            verdict: "perfect",
            feedback: "最佳应对。证据保全是追赃关键。",
            nextNodeId: null,
            awarenessDelta: 30,
            lossDelta: 0,
          },
          {
            text: "删除短信，不予理会",
            emoji: "🗑️",
            verdict: "warn",
            feedback: "止损但放弃追赃，也未预警扩散。",
            nextNodeId: null,
            awarenessDelta: 5,
            lossDelta: 20,
          },
        ],
      },
    ],
    endings: [
      {
        id: "ending_s",
        rank: "S",
        kind: "rescued",
        title: "完美识破 · 链上冻结",
        desc: "你通过官方 APP 核实识破钓鱼，报案后链上资金冻结率 95%。",
        minAwareness: 90,
        maxLoss: 5,
        weaknessIntel: {
          enemyTypeId: "digitalRmbAuth",
          damageBonus: 0.2,
          desc: "授权页面存在 LOGO 像素差异，塔防中对该敌人 +20% 伤害",
        },
        hotline: "96110 反诈专线，数字人民币诈骗请立即举报。",
      },
      {
        id: "ending_a",
        rank: "A",
        kind: "rescued",
        title: "成功识破 · 部分追赃",
        desc: "你识别威胁话术后止损，报案追回 60% 资金。",
        minAwareness: 60,
        maxLoss: 30,
        weaknessIntel: {
          enemyTypeId: "digitalRmbAuth",
          damageBonus: 0.15,
          desc: "授权页面有破绽，塔防中对该敌人 +15% 伤害",
        },
        hotline: "96110 反诈专线，数字人民币诈骗请立即举报。",
      },
      {
        id: "ending_b",
        rank: "B",
        kind: "partialLoss",
        title: "止损 · 信息泄露",
        desc: "你点击链接但未输入授权码，已泄露部分信息。",
        minAwareness: 30,
        maxLoss: 60,
        hotline: "96110 反诈专线，及时修改钱包密码。",
      },
      {
        id: "ending_c",
        rank: "C",
        kind: "totalLoss",
        title: "受骗 · 全额损失",
        desc: "你输入授权码，钱包资产被瞬间转走。",
        minAwareness: 0,
        maxLoss: 100,
        hotline: "96110 反诈专线，立即报案申请链上冻结。",
      },
    ],
    takeaways: [
      "数字人民币官方钱包只在指定应用商店下载",
      "授权码 = 钱包控制权，绝不外泄",
      "'影响征信'是经典恐吓话术",
      "征信只能本人到央行或官方渠道查询",
    ],
  },

  // 剧本 3：加密货币杀猪盘
  {
    id: "vsim_cryptoPig",
    typeId: "cryptoPigButcher",
    typeName: "加密货币杀猪盘",
    title: "嗨，我加错人了",
    victimProfile: "单身白领",
    difficulty: 4,
    scenario: "你是 32 岁的单身白领，某天社交平台收到一条'误加好友'消息……",
    startNodeId: "node_1",
    nodes: [
      {
        id: "node_1",
        title: "第一阶段：社交接触",
        scene: "社交平台弹出消息：'嗨，我加错人了，但觉得你很有气质。'对方头像是精致女性，朋友圈全是旅行美食。",
        scammerLine: "嗨，我加错人了，但觉得你很有气质。能交个朋友吗？",
        psychology: ["误加好友话术", "精致人设", "情感渗透"],
        redFlag: 3,
        choices: [
          {
            text: "不回应，直接拉黑",
            emoji: "🚫",
            verdict: "perfect",
            feedback: "最佳拦截。陌生异性主动 + 精致头像 = 杀猪盘典型特征。",
            nextNodeId: "node_2",
            awarenessDelta: 35,
            lossDelta: 0,
          },
          {
            text: "回应但保持警惕，不谈感情",
            emoji: "🤔",
            verdict: "ok",
            feedback: "方向正确但风险仍在，杀猪盘擅长长期渗透。",
            nextNodeId: "node_2",
            awarenessDelta: 15,
            lossDelta: 10,
          },
          {
            text: "积极回应，开始情感交流",
            emoji: "💕",
            verdict: "wrong",
            feedback: "致命错误。这正是'养猪'阶段，情感投入越深损失越大。",
            nextNodeId: "node_2",
            awarenessDelta: 0,
            lossDelta: 40,
          },
        ],
      },
      {
        id: "node_2",
        title: "第二阶段：投资话术",
        scene: "对方每日嘘寒问暖后，'不经意'提及：'我表哥在币圈有内部消息，上周赚了 30 万。'并分享收益截图。",
        scammerLine: "我表哥在币圈有内部消息，上周赚了 30 万。你要不要一起？稳赚不赔。",
        psychology: ["内部消息话术", "收益截图", "稳赚承诺"],
        redFlag: 5,
        choices: [
          {
            text: "立即识别杀猪盘，拉黑 + 举报",
            emoji: "🚨",
            verdict: "perfect",
            feedback: "最佳拦截。'网恋+投资'是杀猪盘铁证。",
            nextNodeId: "node_3",
            awarenessDelta: 35,
            lossDelta: 0,
          },
          {
            text: "表示对投资不感兴趣，但继续聊天",
            emoji: "🙅",
            verdict: "warn",
            feedback: "止损但不彻底，对方会换话术继续渗透。",
            nextNodeId: "node_3",
            awarenessDelta: 10,
            lossDelta: 15,
          },
          {
            text: "感兴趣，询问如何参与",
            emoji: "💰",
            verdict: "wrong",
            feedback: "致命错误。'内部消息''稳赚不赔'是杀猪盘核心话术。",
            nextNodeId: "node_3",
            awarenessDelta: 0,
            lossDelta: 50,
          },
        ],
      },
      {
        id: "node_3",
        title: "第三阶段：资金拦截",
        scene: "对方引导下载陌生 APP，前期小额提现成功（投入 1000 元，提现 1200 元），现在要求投入 50 万'大单'。",
        scammerLine: "这次是大单，最低 50 万起，三天翻倍。你先投 50 万，三天后连本带利 100 万。",
        psychology: ["前期甜头", "大单催促", "翻倍诱惑"],
        redFlag: 5,
        choices: [
          {
            text: "立即提现所有资金 + 拉黑 + 报案",
            emoji: "🏃",
            verdict: "perfect",
            feedback: "最佳应对。前期可提现是诱饵，立即撤退是唯一正确选择。",
            nextNodeId: null,
            awarenessDelta: 30,
            lossDelta: 0,
          },
          {
            text: "继续观望，再投入 5 万试水",
            emoji: "🤞",
            verdict: "wrong",
            feedback: "致命错误。'试水'只会让沉没成本加深，最终全损。",
            nextNodeId: null,
            awarenessDelta: 0,
            lossDelta: 50,
          },
        ],
      },
    ],
    endings: [
      {
        id: "ending_s",
        rank: "S",
        kind: "rescued",
        title: "完美识破 · 团伙被端",
        desc: "你在接触阶段识破杀猪盘，报案后团伙被端，链上资金冻结率 95%。",
        minAwareness: 90,
        maxLoss: 5,
        weaknessIntel: {
          enemyTypeId: "cryptoPigButcher",
          damageBonus: 0.2,
          desc: "杀猪盘依赖情感光环，识破后光环失效，塔防中对该敌人 +20% 伤害",
        },
        hotline: "96110 反诈专线，加密货币诈骗可申请链上资金冻结。",
      },
      {
        id: "ending_a",
        rank: "A",
        kind: "rescued",
        title: "成功识破 · 部分追赃",
        desc: "你在投资阶段识破，报案追回 60% 资金。",
        minAwareness: 60,
        maxLoss: 30,
        weaknessIntel: {
          enemyTypeId: "cryptoPigButcher",
          damageBonus: 0.15,
          desc: "杀猪盘话术有破绽，塔防中对该敌人 +15% 伤害",
        },
        hotline: "96110 反诈专线，加密货币诈骗可申请链上资金冻结。",
      },
      {
        id: "ending_b",
        rank: "B",
        kind: "partialLoss",
        title: "止损 · 沉没成本",
        desc: "你小额投入后识破，损失前期投入。",
        minAwareness: 30,
        maxLoss: 60,
        hotline: "96110 反诈专线，及时止损是关键。",
      },
      {
        id: "ending_c",
        rank: "C",
        kind: "totalLoss",
        title: "受骗 · 全额损失",
        desc: "你投入大额资金后 APP 跑路，对方失联。",
        minAwareness: 0,
        maxLoss: 100,
        hotline: "96110 反诈专线，立即报案提供链上地址。",
      },
    ],
    takeaways: [
      "陌生异性主动搭讪 + 精致头像 = 杀猪盘典型特征",
      "'网恋+投资'组合必是杀猪盘",
      "'内部消息''稳赚不赔'是核心话术",
      "前期可提现是诱饵，大额投入后必跑路",
    ],
  },

  // 剧本 4：AI 换脸敲诈
  {
    id: "vsim_aiBlackmail",
    typeId: "aiBlackmail",
    typeName: "AI 换脸敲诈",
    title: "不转账就发布视频",
    victimProfile: "公职人员",
    difficulty: 3,
    scenario: "你是 45 岁的公职人员。某天收到陌生邮件，附件是一段不雅视频，主角的脸与你高度相似……",
    startNodeId: "node_1",
    nodes: [
      {
        id: "node_1",
        title: "第一阶段：敲诈识别",
        scene: "邮件正文：'视频已备份。3 天内打 5 万到指定账户，否则发布到所有亲友和单位。'附你的通讯录截图（泄露自某社交平台）。",
        scammerLine: "视频已备份。3 天内打 5 万到指定账户，否则发布到所有亲友和单位。",
        psychology: ["隐私威胁", "时间压力", "通讯录恐吓"],
        redFlag: 5,
        choices: [
          {
            text: "立即报案 + 不转账 + 通知单位保卫处",
            emoji: "🚔",
            verdict: "perfect",
            feedback: "最佳应对。AI 换脸敲诈报警是唯一正确选择，转账只会被反复勒索。",
            nextNodeId: "node_2",
            awarenessDelta: 35,
            lossDelta: 0,
          },
          {
            text: "讨价还价，试图压低金额",
            emoji: "💰",
            verdict: "warn",
            feedback: "有风险。讨价还价 = 承认视频有效，对方会更确信你能被勒索。",
            nextNodeId: "node_2",
            awarenessDelta: 10,
            lossDelta: 20,
          },
          {
            text: "完全按对方要求转账",
            emoji: "💸",
            verdict: "wrong",
            feedback: "致命错误。转账不会让视频消失，只会被反复勒索。",
            nextNodeId: "node_2",
            awarenessDelta: 0,
            lossDelta: 60,
          },
        ],
      },
      {
        id: "node_2",
        title: "第二阶段：证据保全",
        scene: "无论上一步如何，需要决定如何处理这段视频证据。",
        scammerLine: "（对方持续发送威胁邮件，附更多截图）",
        psychology: ["持续施压"],
        redFlag: 4,
        choices: [
          {
            text: "保存邮件 + 截图 + 视频原件 + 链上溯源",
            emoji: "📂",
            verdict: "perfect",
            feedback: "最佳应对。完整证据链是定罪关键。",
            nextNodeId: "node_3",
            awarenessDelta: 30,
            lossDelta: 0,
          },
          {
            text: "删除邮件，试图忘记",
            emoji: "🗑️",
            verdict: "wrong",
            feedback: "致命错误。删除证据会让报案无法立案。",
            nextNodeId: "node_3",
            awarenessDelta: 0,
            lossDelta: 30,
          },
        ],
      },
      {
        id: "node_3",
        title: "第三阶段：扩散预警",
        scene: "已报案并保全证据。需要决定是否通知亲友预警。",
        scammerLine: "（警方已介入，但对方威胁要发布到亲友群）",
        psychology: ["扩散威胁"],
        redFlag: 3,
        choices: [
          {
            text: "主动通知亲友 + 单位 + 社交平台举报",
            emoji: "📢",
            verdict: "perfect",
            feedback: "最佳应对。主动预警可化解扩散威胁，让对方失去筹码。",
            nextNodeId: null,
            awarenessDelta: 35,
            lossDelta: 0,
          },
          {
            text: "不通知，担心影响声誉",
            emoji: "🙈",
            verdict: "warn",
            feedback: "可理解但风险大，对方可能真的扩散。",
            nextNodeId: null,
            awarenessDelta: 5,
            lossDelta: 25,
          },
        ],
      },
    ],
    endings: [
      {
        id: "ending_s",
        rank: "S",
        kind: "rescued",
        title: "完美识破 · 团伙落网",
        desc: "你报案 + 证据保全 + 主动预警，警方顺藤摸瓜端掉团伙。",
        minAwareness: 90,
        maxLoss: 5,
        weaknessIntel: {
          enemyTypeId: "aiBlackmail",
          damageBonus: 0.2,
          desc: "AI 换脸敲诈依赖隐私恐吓，主动预警可破，塔防中对该敌人 +20% 伤害",
        },
        hotline: "96110 反诈专线 + 110 报案，AI 换脸敲诈必立案。",
      },
      {
        id: "ending_a",
        rank: "A",
        kind: "rescued",
        title: "成功识破 · 部分扩散",
        desc: "你报案止损，但部分亲友已收到扩散视频。",
        minAwareness: 60,
        maxLoss: 30,
        weaknessIntel: {
          enemyTypeId: "aiBlackmail",
          damageBonus: 0.15,
          desc: "AI 换脸敲诈有破绽，塔防中对该敌人 +15% 伤害",
        },
        hotline: "96110 反诈专线，AI 合成视频可被鉴伪技术识别。",
      },
      {
        id: "ending_b",
        rank: "B",
        kind: "partialLoss",
        title: "止损 · 声誉受损",
        desc: "你小额转账后识破，但部分视频已扩散。",
        minAwareness: 30,
        maxLoss: 60,
        hotline: "96110 反诈专线，AI 合成视频可被鉴伪技术识别。",
      },
      {
        id: "ending_c",
        rank: "C",
        kind: "totalLoss",
        title: "受骗 · 反复勒索",
        desc: "你完全按对方要求转账，被反复勒索直至倾家荡产。",
        minAwareness: 0,
        maxLoss: 100,
        hotline: "96110 反诈专线，立即报案停止转账。",
      },
    ],
    takeaways: [
      "AI 换脸敲诈报警是唯一正确选择",
      "转账不会让视频消失，只会被反复勒索",
      "AI 合成视频可被鉴伪技术识别",
      "主动通知亲友预警可化解扩散威胁",
    ],
  },

  // 剧本 5：NFT 空投钓鱼
  {
    id: "vsim_nftAirdrop",
    typeId: "nftAirdropPhish",
    typeName: "NFT 空投钓鱼",
    title: "免费 NFT 空投",
    victimProfile: "Web3 新手",
    difficulty: 2,
    scenario: "你是 28 岁的设计师，刚接触 Web3。某天在 Discord 看到一个'免费 NFT 空投'公告……",
    startNodeId: "node_1",
    nodes: [
      {
        id: "node_1",
        title: "第一阶段：空投链接核实",
        scene: "Discord 群里有人发：'🚀 限时免费 NFT 空投！点击 http://nft-air.cf 领取，地板价 0.5 ETH，名额有限！'",
        scammerLine: "🚀 限时免费 NFT 空投！点击链接领取，地板价 0.5 ETH，名额有限！",
        psychology: ["限时诱惑", "免费心理", "FOMO"],
        redFlag: 4,
        choices: [
          {
            text: "在官方项目方 Twitter/官网核实空投信息",
            emoji: "🔍",
            verdict: "perfect",
            feedback: "最佳拦截。官方渠道核实是识破钓鱼的第一步。",
            nextNodeId: "node_2",
            awarenessDelta: 35,
            lossDelta: 0,
          },
          {
            text: "点击链接查看，但不连接钱包",
            emoji: "👀",
            verdict: "warn",
            feedback: "有风险。钓鱼网站可能利用 JS 漏洞自动连接钱包。",
            nextNodeId: "node_2",
            awarenessDelta: 10,
            lossDelta: 15,
          },
          {
            text: "完全相信，点击链接并连接钱包",
            emoji: "🔗",
            verdict: "wrong",
            feedback: "致命错误。连接钱包 = 授权，钓鱼网站可瞬间转走所有资产。",
            nextNodeId: "node_2",
            awarenessDelta: 0,
            lossDelta: 60,
          },
        ],
      },
      {
        id: "node_2",
        title: "第二阶段：授权请求识别",
        scene: "页面提示'为领取 NFT，请签名授权'，授权内容是复杂的智能合约代码。",
        scammerLine: "请签名授权以领取 NFT。（授权内容：transferFrom(all)）",
        psychology: ["复杂授权", "信息过载", "免费诱惑"],
        redFlag: 5,
        choices: [
          {
            text: "立即关闭页面 + 用 revoke.cash 检查授权",
            emoji: "🛡️",
            verdict: "perfect",
            feedback: "最佳应对。'transferFrom(all)'= 无限授权，必须立即撤销。",
            nextNodeId: "node_3",
            awarenessDelta: 35,
            lossDelta: 0,
          },
          {
            text: "询问 Discord 群里其他人是否真实",
            emoji: "💬",
            verdict: "warn",
            feedback: "有风险。群里可能全是托儿，会一致说'真的，我领到了'。",
            nextNodeId: "node_3",
            awarenessDelta: 15,
            lossDelta: 10,
          },
          {
            text: "直接签名授权",
            emoji: "✍️",
            verdict: "wrong",
            feedback: "致命错误。'transferFrom(all)'授权后钱包资产被瞬间转走。",
            nextNodeId: "node_3",
            awarenessDelta: 0,
            lossDelta: 60,
          },
        ],
      },
      {
        id: "node_3",
        title: "第三阶段：资产保全",
        scene: "已识别是钓鱼网站。需要决定后续动作。",
        scammerLine: "（对方已无法联系）",
        psychology: [],
        redFlag: 2,
        choices: [
          {
            text: "立即转移所有资产到新钱包 + 撤销所有授权 + 报案",
            emoji: "🚨",
            verdict: "perfect",
            feedback: "最佳应对。资产转移 + 撤销授权 + 报案三管齐下。",
            nextNodeId: null,
            awarenessDelta: 30,
            lossDelta: 0,
          },
          {
            text: "不转移资产，仅撤销授权",
            emoji: "🛡️",
            verdict: "warn",
            feedback: "有风险。已泄露的私钥信息可能被再次利用。",
            nextNodeId: null,
            awarenessDelta: 10,
            lossDelta: 20,
          },
        ],
      },
    ],
    endings: [
      {
        id: "ending_s",
        rank: "S",
        kind: "rescued",
        title: "完美识破 · 资产保全",
        desc: "你通过官方渠道核实识破钓鱼，资产转移 + 撤销授权 + 报案，零损失。",
        minAwareness: 90,
        maxLoss: 5,
        weaknessIntel: {
          enemyTypeId: "nftAirdropPhish",
          damageBonus: 0.2,
          desc: "NFT 钓鱼依赖无限授权，识破后可破，塔防中对该敌人 +20% 伤害",
        },
        hotline: "96110 反诈专线，NFT 钓鱼请立即举报并提供链上地址。",
      },
      {
        id: "ending_a",
        rank: "A",
        kind: "rescued",
        title: "成功识破 · 部分追赃",
        desc: "你识别授权风险后止损，报案追回 60% 资产。",
        minAwareness: 60,
        maxLoss: 30,
        weaknessIntel: {
          enemyTypeId: "nftAirdropPhish",
          damageBonus: 0.15,
          desc: "NFT 钓鱼有破绽，塔防中对该敌人 +15% 伤害",
        },
        hotline: "96110 反诈专线，NFT 钓鱼请立即举报。",
      },
      {
        id: "ending_b",
        rank: "B",
        kind: "partialLoss",
        title: "止损 · 部分授权",
        desc: "你授权后识破，撤销了部分授权，损失部分资产。",
        minAwareness: 30,
        maxLoss: 60,
        hotline: "96110 反诈专线，及时撤销授权。",
      },
      {
        id: "ending_c",
        rank: "C",
        kind: "totalLoss",
        title: "受骗 · 全额损失",
        desc: "你签名无限授权，钱包 NFT 与代币被瞬间转走。",
        minAwareness: 0,
        maxLoss: 100,
        hotline: "96110 反诈专线，立即报案提供链上地址。",
      },
    ],
    takeaways: [
      "NFT 空投认官方渠道（Twitter/官网）",
      "'transferFrom(all)' = 无限授权，等于交出钱包控制权",
      "用 revoke.cash 定期检查并撤销授权",
      "群里晒单都是托，FOMO 是骗局利器",
    ],
  },

  // 剧本 6：AI 投顾诈骗
  {
    id: "vsim_aiInvestAdvisor",
    typeId: "aiInvestAdvisor",
    typeName: "AI 投顾理财诈骗",
    title: "AI 智能选股，稳赚不赔",
    victimProfile: "退休人员",
    difficulty: 3,
    scenario: "你是 60 岁的退休工人，某天在短视频平台看到'AI 智能投顾'广告，号称'AI 选股，年化收益 30%，保本'……",
    startNodeId: "node_1",
    nodes: [
      {
        id: "node_1",
        title: "第一阶段：广告识别",
        scene: "短视频广告：'AI 智能投顾，年化 30%，保本！前 100 名用户免费体验。'附'老师'微信二维码。",
        scammerLine: "AI 智能投顾，年化 30%，保本！前 100 名用户免费体验，加微信领取。",
        psychology: ["高收益承诺", "保本话术", "稀缺诱惑"],
        redFlag: 5,
        choices: [
          {
            text: "识别诈骗，举报广告 + 拉黑",
            emoji: "🚨",
            verdict: "perfect",
            feedback: "最佳拦截。'保本+高收益'是理财诈骗铁证。",
            nextNodeId: "node_2",
            awarenessDelta: 35,
            lossDelta: 0,
          },
          {
            text: "在证监会官网查询机构资质",
            emoji: "🏛️",
            verdict: "ok",
            feedback: "正确方向。证监会官网可查投资咨询资质。",
            nextNodeId: "node_2",
            awarenessDelta: 25,
            lossDelta: 5,
          },
          {
            text: "加微信，询问详情",
            emoji: "💬",
            verdict: "wrong",
            feedback: "致命错误。加微信 = 进入'养猪'阶段，会被持续洗脑。",
            nextNodeId: "node_2",
            awarenessDelta: 0,
            lossDelta: 40,
          },
        ],
      },
      {
        id: "node_2",
        title: "第二阶段：话术识别",
        scene: "对方发来'老师'履历（伪造）+ 群聊截图（全是托儿晒收益）+ '内部通道'链接。",
        scammerLine: "老师从业 20 年，年化 35%。群里的老李上周投了 10 万，这周已经赚了 3 万。你也来吧。",
        psychology: ["伪造履历", "托儿晒单", "内部通道"],
        redFlag: 5,
        choices: [
          {
            text: "识别托儿话术，立即拉黑 + 举报",
            emoji: "🚫",
            verdict: "perfect",
            feedback: "最佳拦截。'群里晒单'+ '内部通道' = 100% 诈骗。",
            nextNodeId: "node_3",
            awarenessDelta: 35,
            lossDelta: 0,
          },
          {
            text: "表示感兴趣但要求看监管备案",
            emoji: "📋",
            verdict: "warn",
            feedback: "方向正确但风险仍在，对方会伪造备案文件。",
            nextNodeId: "node_3",
            awarenessDelta: 15,
            lossDelta: 15,
          },
          {
            text: "完全相信，点击链接下载 APP",
            emoji: "📲",
            verdict: "wrong",
            feedback: "致命错误。陌生 APP 是庞氏骗局前奏，前期可提现是诱饵。",
            nextNodeId: "node_3",
            awarenessDelta: 0,
            lossDelta: 50,
          },
        ],
      },
      {
        id: "node_3",
        title: "第三阶段：资金拦截",
        scene: "无论上一步如何，对方催促'内部通道名额有限，今天最后一天'。",
        scammerLine: "内部通道名额有限，今天最后一天，最低 5 万起投。",
        psychology: ["稀缺催促", "最后通牒"],
        redFlag: 5,
        choices: [
          {
            text: "立即拉黑 + 96110 举报 + 通知亲友预警",
            emoji: "🚔",
            verdict: "perfect",
            feedback: "最佳应对。举报 + 预警可避免更多人受骗。",
            nextNodeId: null,
            awarenessDelta: 30,
            lossDelta: 0,
          },
          {
            text: "讨价还价，试图小额试水",
            emoji: "🤞",
            verdict: "wrong",
            feedback: "致命错误。'试水'只会让沉没成本加深，最终全损。",
            nextNodeId: null,
            awarenessDelta: 0,
            lossDelta: 50,
          },
        ],
      },
    ],
    endings: [
      {
        id: "ending_s",
        rank: "S",
        kind: "rescued",
        title: "完美识破 · 团伙落网",
        desc: "你在广告阶段识破诈骗，举报后团伙被端，亲友零损失。",
        minAwareness: 90,
        maxLoss: 5,
        weaknessIntel: {
          enemyTypeId: "aiInvestAdvisor",
          damageBonus: 0.2,
          desc: "AI 投顾诈骗依赖'保本+高收益'话术，识破后可破，塔防中对该敌人 +20% 伤害",
        },
        hotline: "96110 反诈专线 + 证监会举报热线 12386。",
      },
      {
        id: "ending_a",
        rank: "A",
        kind: "rescued",
        title: "成功识破 · 部分预警",
        desc: "你在话术阶段识破，举报但部分亲友已接触广告。",
        minAwareness: 60,
        maxLoss: 30,
        weaknessIntel: {
          enemyTypeId: "aiInvestAdvisor",
          damageBonus: 0.15,
          desc: "AI 投顾话术有破绽，塔防中对该敌人 +15% 伤害",
        },
        hotline: "96110 反诈专线 + 证监会举报热线 12386。",
      },
      {
        id: "ending_b",
        rank: "B",
        kind: "partialLoss",
        title: "止损 · 沉没成本",
        desc: "你小额投入后识破，损失前期投入。",
        minAwareness: 30,
        maxLoss: 60,
        hotline: "96110 反诈专线，及时止损是关键。",
      },
      {
        id: "ending_c",
        rank: "C",
        kind: "totalLoss",
        title: "受骗 · 全额损失",
        desc: "你投入大额资金后 APP 跑路，'老师'失联。",
        minAwareness: 0,
        maxLoss: 100,
        hotline: "96110 反诈专线，立即报案。",
      },
    ],
    takeaways: [
      "'保本+高收益'是理财诈骗铁证",
      "证监会官网可查投资咨询资质",
      "群里晒单都是托儿",
      "'内部通道'+稀缺催促 = 100% 诈骗",
    ],
  },
];

// ====================================================================
// D4：自定义难度预设档位
// ====================================================================

export const CUSTOM_DIFFICULTY_PRESETS: Record<CustomDifficultyPreset, CustomDifficultyConfig> = {
  easy: {
    enemyHpMul: 0.7,
    enemySpeedMul: 0.8,
    enemyDmgMul: 0.7,
    spawnIntervalMul: 1.3,
    startEnergy: 150,
    baseHpMul: 1.3,
  },
  normal: {
    enemyHpMul: 1.0,
    enemySpeedMul: 1.0,
    enemyDmgMul: 1.0,
    spawnIntervalMul: 1.0,
    startEnergy: 100,
    baseHpMul: 1.0,
  },
  hard: {
    enemyHpMul: 1.4,
    enemySpeedMul: 1.15,
    enemyDmgMul: 1.3,
    spawnIntervalMul: 0.8,
    startEnergy: 80,
    baseHpMul: 0.85,
  },
  custom: {
    enemyHpMul: 1.0,
    enemySpeedMul: 1.0,
    enemyDmgMul: 1.0,
    spawnIntervalMul: 1.0,
    startEnergy: 100,
    baseHpMul: 1.0,
  },
};

// ====================================================================
// 工具函数：根据 typeId 获取 v11 敌人定义
// ====================================================================

export function getV11Enemy(typeId: string): EnemyDef | undefined {
  return ENEMIES_V11[typeId];
}

/** 根据 typeId 获取 v11 BOSS 定义 */
export function getV11Boss(bossId: string): BossRushDef | undefined {
  return BOSSES_V11.find((b) => b.id === bossId);
}

/** 根据 bossId 获取 v11 BOSS 剧情对白 */
export function getV11BossDialogue(bossId: string): BossDialogue | undefined {
  return BOSS_DIALOGUES_V11.find((d) => d.bossId === bossId);
}

/** 根据 caseId 获取 v11 真实案例 */
export function getV11RealCase(caseId: string): RealCaseDef | undefined {
  return REAL_CASES_V11.find((c) => c.id === caseId);
}

/** 根据 caseId 获取 v11 案例五步复盘 */
export function getV11CaseBreakdown(caseId: string): CaseBreakdownDef | undefined {
  return CASE_BREAKDOWNS_V11.find((c) => c.caseId === caseId);
}

/** 根据 enemyId 获取 v11 案例五步复盘（关联 refEnemyId） */
export function getV11CaseBreakdownByEnemyId(enemyId: string): CaseBreakdownDef | undefined {
  return CASE_BREAKDOWNS_V11.find((c) => {
    const realCase = REAL_CASES_V11.find((rc) => rc.id === c.caseId);
    return realCase?.refEnemyId === enemyId;
  });
}

/** 根据 scenarioId 获取受害人模拟剧本 */
export function getVictimSimScenario(scenarioId: string): VictimSimScenario | undefined {
  return VICTIM_SIM_SCENARIOS_V11.find((s) => s.id === scenarioId);
}

/** 根据 typeId 获取该诈骗类型的受害人模拟剧本 */
export function getVictimSimScenarioByTypeId(typeId: string): VictimSimScenario | undefined {
  return VICTIM_SIM_SCENARIOS_V11.find((s) => s.typeId === typeId);
}

/** 获取预设档位的难度配置 */
export function getPresetConfig(preset: CustomDifficultyPreset): CustomDifficultyConfig {
  return { ...CUSTOM_DIFFICULTY_PRESETS[preset] };
}
